import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const header = (
    <header className={'flex flex-row border w-full text-4xl '}>
      <Link href='/'>header</Link>
    </header>
  )

  const footer = (
    <footer className={'flex flex-row border w-full text-4xl '}>
      footer
    </footer>
  )
  return (
    <html lang="en">
      <body className={'flex flex-col justify-center items-center mx-auto '}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
